### ISSUE TITLE
Migrate to Grails 3

### ISSUE THREAD

**Issue by koctob** [dustindclark/grails-timezone-detection#3]
| Error Error initializing classpath: Could not find any matches for org.grails.
plugins:timezone-detection:latest.integration as no versions of org.grails.plugi
ns:timezone-detection are available.
Searched in the following locations:
    file:/C:/Users/user/.m2/repository/org/grails/plugins/timezone-detection/
maven-metadata.xml
    file:/C:/Users/user/.m2/repository/org/grails/plugins/timezone-detection/

    https://repo.grails.org/grails/core/org/grails/plugins/timezone-detection/ma
ven-metadata.xml
    https://repo.grails.org/grails/core/org/grails/plugins/timezone-detection/
Required by:
    project:project:0.1 (Use --stacktrace to see the full trace)

grails 3.0

**Comment by atulgirishkumar** [comment]
I am facing the same issue. Can you suggest something @dustindclark 

Thanks in advance!

**Comment by dustindclark** [comment]
I have not migrated this plugin to Grails 3 yet.  There's not much to the plugin though, so there shouldn't be much to it.  Feel free to submit a PR.  Otherwise, I'll try to look at this in the near future.

**Comment by piperpilot** [comment]
+1 for upgrade

**Comment by pjdvmalan** [comment]
I am in the process of migrating the plugin to Grails 3 (and submit the PR once done), but am stuck with the following: https://stackoverflow.com/questions/49017561/how-would-i-overwrite-a-method-in-a-taglib-bean.

Please let me know if anyone can be of assistance.

**Comment by dustindclark** [comment]
Just replied on SO, but it's not the best solution.  You may try the Grails Slack channel as well.  Thanks for working on the upgrade...it's on my list, but haven't gotten around to it.

**Comment by pjdvmalan** [comment]
Thanks for your input @dustindclark. All is working as expected - when using the Grails 3 version of the plugin in a sample project it works.

I am, however, struggling to get the unit tests covering `formatDate` and `datePicker` to work, but that may just me not understanding how to do it properly.

I have a working prototype and will update a fork for you to review.

**Comment by pjdvmalan** [comment]
Hi @dustindclark - before I submit a merge request, I would like to confirm the following with you:

I tried to use the same mechanism you used to **overwrite** the defaullt `datePicker` and `formatDate` Grails tags. I could not get **DI** working either. I then tried to use **inheritance**, but since I need to change the attrs _before_ calling the parent constructor, this also posed some problems.

The solution I ended up with was to create the `datePicker` and `formatDate` tags within the `tz` name space.

All is now working as expected, including the unit tests (see the followin [SO](https://stackoverflow.com/questions/49203808/how-do-i-unit-test-a-taglib-that-calls-g-formatdate) ticket).

The fork is up to date - so please have a look and let me know if you have any concerns with this approach. If not, I would appreciate any suggestions you may be able to put forward.

**Comment by dustindclark** [comment]
Hi @pjdvmalan.  Thanks for the work on the upgrade!  I would really prefer to override the datePicker...especially since those upgrading Grails apps may not notice the change or discrepancy with times.  This could cause data corruption that would be difficult to clean up.

It will probably be next week, but I will take a look at your fork and see if I can get the override working.  Thanks again!

**Comment by pjdvmalan** [comment]
I agree that overriding it would be the appropriate solution. I am happy to help where I can - but this one really stumped me!
